name: CI

on:

  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo "Hola Mundo Test"

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with: 
          java-version: '1.8'
          distribution: 'adopt'

      - name: SonarCloud Analysis
        run: |
          chmod +x gradlew
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_LAB_JAVA }}
