name: CI

on:

  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo "Hola Mundo Test"

      - name: Generate Jacoco Coverage Report
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport

      - name: SonarCloud Analysis
        run: |
          chmod +x gradlew
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_LAB_JAVA }}
          

      - name: SonarQube Quality Gate Check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env: 
          organization: devopslabuoh
          project: UOHuser_microservicio-java
          SONAR_TOKEN: ${{ secrets.TOKEN_LAB_JAVA }}
          SONAR_HOST_URL: https://sonarcloud.io
          wait-for-quality-gate: true
        with: 
          scanMetadataReportFile: build/sonar/report-task.txt

      
