name: CI

on:

  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo "Hola Mundo Test"

      - name: Generate Jacoco Coverage Report
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport

      - name: SonarCloud Analysis
        run: |
          chmod +x gradlew
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_LAB_JAVA }}
          
      - name: SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.TOKEN_LAB_JAVA }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_QUALITYGATE: 'Cobertura'
          wait-for-quality-gate: true
        with: 
          scanMetadataReportFile: build/sonar/report-task.txt

      - name: Copiar JAR generado
        run: cp build/libs/*.jar src/microservicio.jar

      
