name: CI

on:

  push:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: build gradle
        run: |
          chmod +x gradlew
          ./gradlew build
          ls -ltr

      - name: Generate Jacoco Coverage Report
        run: |
          chmod +x gradlew
          ./gradlew jacocoTestReport

      - name: SonarCloud Analysis
        run: |
          chmod +x gradlew
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_LAB_JAVA }}
          
      - name: SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env: 
          SONAR_TOKEN: ${{ secrets.TOKEN_LAB_JAVA }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_QUALITYGATE: 'Cobertura'
          wait-for-quality-gate: true
        with: 
          scanMetadataReportFile: build/sonar/report-task.txt
      
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copia de Jar a Raiz de proyecto
        run: |
          cp $GITHUB_WORKSPACE/build/libs/*.jar .
          chmod 777 *.jar
          ls -lt 
    
      - name: Docker Build
        run: | 
          docker build --tag dockeruser701/useruoh:latest .
          docker images

      - name: Docker Push
        run: |
          docker push dockeruser701/useruoh 

  deploy: 
    runs-on: self-hosted 
    needs: build
    steps: 

    - uses: actions/checkout@v3
    
    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yml        